// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/protocol/worker.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Failure int32

const (
	Failure_FAILURE_UNSPECIFIED  Failure = 0
	Failure_FAILURE_PROVE_FAILED Failure = 1
)

// Enum value maps for Failure.
var (
	Failure_name = map[int32]string{
		0: "FAILURE_UNSPECIFIED",
		1: "FAILURE_PROVE_FAILED",
	}
	Failure_value = map[string]int32{
		"FAILURE_UNSPECIFIED":  0,
		"FAILURE_PROVE_FAILED": 1,
	}
)

func (x Failure) Enum() *Failure {
	p := new(Failure)
	*p = x
	return p
}

func (x Failure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Failure) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_worker_proto_enumTypes[0].Descriptor()
}

func (Failure) Type() protoreflect.EnumType {
	return &file_internal_protocol_worker_proto_enumTypes[0]
}

func (x Failure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Failure.Descriptor instead.
func (Failure) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_worker_proto_rawDescGZIP(), []int{0}
}

type Ready struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      uint32                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Artifact      string                 `protobuf:"bytes,2,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_internal_protocol_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_internal_protocol_worker_proto_rawDescGZIP(), []int{0}
}

func (x *Ready) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *Ready) GetArtifact() string {
	if x != nil {
		return x.Artifact
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Witness       []byte                 `protobuf:"bytes,2,opt,name=witness,proto3" json:"witness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_protocol_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_protocol_worker_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetWitness() []byte {
	if x != nil {
		return x.Witness
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Proof         []byte                 `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	Public        []byte                 `protobuf:"bytes,3,opt,name=public,proto3" json:"public,omitempty"`
	Failure       Failure                `protobuf:"varint,4,opt,name=failure,proto3,enum=veil402.worker.v1.Failure" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_protocol_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_protocol_worker_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *Response) GetPublic() []byte {
	if x != nil {
		return x.Public
	}
	return nil
}

func (x *Response) GetFailure() Failure {
	if x != nil {
		return x.Failure
	}
	return Failure_FAILURE_UNSPECIFIED
}

var File_internal_protocol_worker_proto protoreflect.FileDescriptor

const file_internal_protocol_worker_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/protocol/worker.proto\x12\x11veil402.worker.v1\"?\n" +
	"\x05Ready\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x1a\n" +
	"\bartifact\x18\x02 \x01(\tR\bartifact\"3\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\awitness\x18\x02 \x01(\fR\awitness\"~\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12\x16\n" +
	"\x06public\x18\x03 \x01(\fR\x06public\x124\n" +
	"\afailure\x18\x04 \x01(\x0e2\x1a.veil402.worker.v1.FailureR\afailure*<\n" +
	"\aFailure\x12\x17\n" +
	"\x13FAILURE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14FAILURE_PROVE_FAILED\x10\x01BLZJgithub.com/veil402/veil402/prover/veil402-gnark/internal/protocol;protocolb\x06proto3"

var (
	file_internal_protocol_worker_proto_rawDescOnce sync.Once
	file_internal_protocol_worker_proto_rawDescData []byte
)

func file_internal_protocol_worker_proto_rawDescGZIP() []byte {
	file_internal_protocol_worker_proto_rawDescOnce.Do(func() {
		file_internal_protocol_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_worker_proto_rawDesc), len(file_internal_protocol_worker_proto_rawDesc)))
	})
	return file_internal_protocol_worker_proto_rawDescData
}

var file_internal_protocol_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_protocol_worker_proto_goTypes = []any{
	(Failure)(0),     // 0: veil402.worker.v1.Failure
	(*Ready)(nil),    // 1: veil402.worker.v1.Ready
	(*Request)(nil),  // 2: veil402.worker.v1.Request
	(*Response)(nil), // 3: veil402.worker.v1.Response
}
var file_internal_protocol_worker_proto_depIdxs = []int32{
	0, // 0: veil402.worker.v1.Response.failure:type_name -> veil402.worker.v1.Failure
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_protocol_worker_proto_init() }
func file_internal_protocol_worker_proto_init() {
	if File_internal_protocol_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_worker_proto_rawDesc), len(file_internal_protocol_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_worker_proto_goTypes,
		DependencyIndexes: file_internal_protocol_worker_proto_depIdxs,
		EnumInfos:         file_internal_protocol_worker_proto_enumTypes,
		MessageInfos:      file_internal_protocol_worker_proto_msgTypes,
	}.Build()
	File_internal_protocol_worker_proto = out.File
	file_internal_protocol_worker_proto_goTypes = nil
	file_internal_protocol_worker_proto_depIdxs = nil
}
