// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ready {
    #[prost(uint32, tag = "1")]
    pub protocol: u32,
    #[prost(string, tag = "2")]
    pub artifact: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Request {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub witness: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Response {
    #[prost(uint64, tag = "1")]
    pub id: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub proof: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub public: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "Failure", tag = "4")]
    pub failure: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Failure {
    Unspecified = 0,
    ProveFailed = 1,
}
impl Failure {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FAILURE_UNSPECIFIED",
            Self::ProveFailed => "FAILURE_PROVE_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FAILURE_UNSPECIFIED" => Some(Self::Unspecified),
            "FAILURE_PROVE_FAILED" => Some(Self::ProveFailed),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
